=== ETHZ-TEC/FlockLab2-Server/webserver/xml/flocklab.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
	/*
	 * XML schema for FlockLab test configuration XMLs. 
	 * This schema can be downloaded from http://www.flocklab.ethz.ch/user/xml/flocklab.xsd
	 * Help is available at http://www.flocklab.ethz.ch/wiki/wiki/Public/Man/XmlConfig
 	 *
 	 *
	 * __author__      = "Christoph Walser <walser@tik.ee.ethz.ch>"
	 * __copyright__   = "Copyright 2011-2014, ETH Zurich, Switzerland"
	 * __license__     = "GPL"
	 * __id__          = "$Id$"
	 */
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.flocklab.ethz.ch" xmlns="http://www.flocklab.ethz.ch" elementFormDefault="qualified">

<!-- ############################################################################### 
     # The following block is the main schema for a FlockLab test.                 #
     # It defines which elements have to be present in a valid XML configuration.  #
     ############################################################################### -->
<!-- testConf is the root element of the XML schema. It can only be present once. -->
<xs:element name="testConf">
  <xs:complexType>
    <xs:sequence>
      <xs:group ref="services" minOccurs="0" maxOccurs="unbounded"/>
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:sequence>
          <xs:element name="generalConf" type="generalConfType" minOccurs="1" maxOccurs="1"/>
          <xs:group ref="services" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="targetConf" type="targetConfType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:sequence>
          <xs:element name="targetConf" type="targetConfType" minOccurs="1" maxOccurs="unbounded"/>
          <xs:group ref="services" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="generalConf" type="generalConfType" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
      </xs:choice>
      <xs:group ref="services" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!-- ############################################################################### 
     # Choice of available services                                                #
     ############################################################################### -->
<xs:group name="services">
  <xs:choice>
    <!-- Serial service configuration. If service is not to be used, do not specify this element. -->
    <xs:element name="serialConf" type="serialConfType"/>
    <!-- GPIO tracing service configuration. If service is not to be used, do not specify this element. -->
    <xs:element name="gpioTracingConf" type="gpioTracingConfType"/>
    <!-- GPIO actuation service configuration. If service is not to be used, do not specify this element. -->
    <xs:element name="gpioActuationConf" type="gpioActuationConfType"/>
    <!-- Power profiling service configuration. If service is not to be used, do not specify this element. -->
    <xs:element name="powerProfilingConf" type="powerProfilingConfType"/>
    <!-- Target image configuration. If only images from database are to be used, do not specify this element. -->
    <xs:element name="imageConf" type="imageConfType"/>
  </xs:choice>
</xs:group>


<!-- ############################################################################### 
     # The following blocks define the types of elements used in the main block    #
     # above.                                                                      #
     ############################################################################### -->
<!-- All elements needed for the general setup of a single FlockLab test -->
<xs:complexType name="generalConfType">
  <xs:sequence>
    <xs:element name="name">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="5"/>
          <xs:maxLength value="45"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="description" minOccurs="0">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:maxLength value="512"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:choice>
      <xs:element name="scheduleAbsolute">
        <xs:complexType>
          <xs:group ref="testDurationAbsoluteGroup"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="scheduleAsap">
        <xs:complexType>
          <xs:all>
            <xs:element name="durationSecs" type="testDurationSecsType"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:choice>
    <xs:element name="emailResults" minOccurs="0" default="no">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="yes|no"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
</xs:complexType>

      
<!-- Configuration of target adapters -->
<xs:complexType name="targetConfType">
  <xs:sequence>
    <xs:element name="obsIds" type="obsIdListRestType"/>
    <xs:element name="targetIds" type="targetIdListRestType" minOccurs="0"/>
    <xs:element name="voltage" minOccurs="0" default="3.3">
      <xs:simpleType>
        <xs:restriction base="xs:decimal">
          <xs:minInclusive value="1.8"/>
          <xs:maxInclusive value="3.6"/>
          <xs:fractionDigits value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:choice>
      <xs:group ref="targetimages" minOccurs="1" maxOccurs="4"/>
      <xs:element name="noImage" type="slotNrType"/>
    </xs:choice>
  </xs:sequence>
</xs:complexType>

<!-- ############################################################################### 
     # Choice of for target images                                                 #
     ############################################################################### -->
<xs:group name="targetimages">
  <xs:choice>
    <xs:element name="dbImageId" type="xs:integer"/>
    <xs:element name="embeddedImageId" type="embeddedImageIdType"/>
  </xs:choice>
</xs:group>

<!-- Configuration of target images -->
<xs:complexType name="imageConfType">
  <xs:all>
    <xs:element name="embeddedImageId" type="embeddedImageIdType"/>
    <xs:element name="name">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="5"/>
          <xs:maxLength value="45"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="description" minOccurs="0">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:maxLength value="512"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="platform" type="platformType"/>
    <xs:element name="os" type="osType" minOccurs="0" maxOccurs="1"/>
    <xs:element name="data" type="xs:base64Binary"/>
	<xs:element name="core" type="xs:integer" minOccurs="0" maxOccurs="1"/>
  </xs:all>
</xs:complexType>


<!-- Configuration of the serial service -->
<xs:complexType name="serialConfType">
  <xs:all>
    <xs:element name="obsIds" type="obsIdListRestType"/>
    <xs:element name="port"  minOccurs="0">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="usb|serial"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="baudrate" minOccurs="0">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:enumeration value="2400"/>
          <xs:enumeration value="4800"/>
          <xs:enumeration value="9600"/>
          <xs:enumeration value="19200"/>
          <xs:enumeration value="38400"/>
          <xs:enumeration value="57600"/>
          <xs:enumeration value="115200"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="mode" minOccurs="0">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="pck|ascii|raw"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="remoteIp" type="ipType" minOccurs="0"/>
  </xs:all>
</xs:complexType>


<!-- Configuration of the GPIO tracing service -->
<xs:complexType name="gpioTracingConfType">
  <xs:sequence>
    <xs:element name="obsIds" type="obsIdListRestType"/>
    <xs:choice>
      <xs:element name="pinConf" type="gpioTracingPinConfType" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="pins" type="pinTracingListType"/>
    </xs:choice>
  </xs:sequence>
</xs:complexType>
<xs:complexType name="gpioTracingPinConfType">
  <xs:sequence>
    <xs:element name="pin" type="pinTracingType"/>
    <xs:element name="edge">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="rising|falling|both"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:element name="mode">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="single|continuous"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    <xs:choice minOccurs="0" maxOccurs="1">
      <xs:element name="callbackGpioActAdd">
        <xs:complexType>
          <xs:group ref="gpioTracCallbackActAddGroup"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="callbackPowerProfAdd">
        <xs:complexType>
          <xs:group ref="gpioTraccallbackPowerProfAddGroup"/>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:sequence>
</xs:complexType>


<!-- Configuration of the GPIO actuation service -->
<xs:complexType name="gpioActuationConfType">
  <xs:sequence>
    <xs:element name="obsIds" type="obsIdListRestType"/>
    <xs:element name="pinConf" type="gpioActuationPinConfType" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>
<xs:complexType name="gpioActuationPinConfType">
  <xs:sequence>
    <xs:element name="pin" type="pinActType"/>
    <xs:element name="level" type="pinActLevelType"/>
    <xs:element name="periodic" minOccurs="0" maxOccurs="1">
      <xs:complexType>
        <xs:group ref="gpioActuationPeriodicGroup"/>
      </xs:complexType>
    </xs:element>
    <xs:choice>
      <xs:element name="relativeTime">
        <xs:complexType>
          <xs:group ref="timingRelativeGroup"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="absoluteTime">
        <xs:complexType>
          <xs:group ref="timingAbsoluteGroup"/>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:sequence>
</xs:complexType>


<!-- Configuration of the power profiling service -->
<xs:complexType name="powerProfilingConfType">
  <xs:sequence>
    <xs:element name="obsIds" type="obsIdListRestType"/>
    <xs:element name="profConf" type="profConfType" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>
<xs:complexType name="profConfType">
  <xs:sequence>
    <xs:element name="durationMillisecs" type="powerProfDurationType"/>
    <xs:choice>
      <xs:element name="relativeTime">
        <xs:complexType>
          <xs:group ref="timingRelativeGroup"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="absoluteTime">
        <xs:complexType>
          <xs:group ref="timingAbsoluteGroup"/>
        </xs:complexType>
      </xs:element>
    </xs:choice>
    <xs:element name="samplingDivider" type="powerProfSamplingDividerType" minOccurs="0" maxOccurs="1"/>
  </xs:sequence>
</xs:complexType>


<!-- ############################################################################### 
     # The following blocks define helper types for custom types that are used in  #
     # several configurations.                                                     #
     ############################################################################### -->

<!-- Type definition for platforms -->
<xs:simpleType name="platformType">
  <xs:restriction base="xs:string">
    <xs:pattern value="dpp|dpp2lora|dpp2lorahg|nrf5"/>
  </xs:restriction>
</xs:simpleType>

<!-- Type definition for operating systems -->
<xs:simpleType name ="osType">
  <xs:restriction base="xs:string">
    <xs:pattern value="contiki|tinyos|other"/>
  </xs:restriction>
</xs:simpleType>

<!-- Type definitions for observer IDs -->
<xs:simpleType name="obsIdListRestType">
  <xs:restriction base="obsIdListType">
  	<xs:minLength value="1"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="obsIdListType">
  <xs:list itemType="obsIdType"/>
</xs:simpleType>

<xs:simpleType name="obsIdType">
  <xs:restriction base="xs:string">
    <xs:pattern value="2|02|4|04|5|05|6|06|7|07|8|08|9|09|10|11|12|ALL"/>
  </xs:restriction>
</xs:simpleType>

<!-- Type definition for target IDs -->
<xs:simpleType name="targetIdListRestType">
  <xs:restriction base="targetIdListType">
  	<xs:minLength value="1"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="targetIdListType">
  <xs:list itemType="xs:unsignedShort"/>
</xs:simpleType>

<!-- Type definition for embedded target image IDs -->
<xs:simpleType name="embeddedImageIdType">
  <xs:restriction base="xs:string">
    <xs:pattern value="([a-zA-Z0-9_])+"/>
  </xs:restriction>
</xs:simpleType>

<!-- Type definition for tracable GPIOs -->
<xs:simpleType name="pinTracingType">
  <xs:restriction base="xs:string">
    <xs:pattern value="INT1|INT2|LED1|LED2|LED3"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="pinTracingListType">
  <xs:list itemType="pinTracingType"/>
</xs:simpleType>

<!-- Type definition for actuation enabled GPIOs -->
<xs:simpleType name="pinActType">
  <xs:restriction base="xs:string">
    <xs:pattern value="SIG1|SIG2|RST"/>
  </xs:restriction>
</xs:simpleType>

<!-- Type definition for actuation enabled GPIO levels -->
<xs:simpleType name="pinActLevelType">
  <xs:restriction base="xs:string">
    <xs:pattern value="low|high|toggle"/>
  </xs:restriction>
</xs:simpleType>

<!-- Group definitions for GPIO tracing callbacks -->
<xs:group name="gpioTracCallbackActAddGroup">
  <xs:all>
    <xs:element name="pin" type="pinActType"/>
    <xs:element name="level" type="pinActLevelType"/>
    <xs:element name="offsetSecs" type="offsetSecsType"/>
    <xs:element name="offsetMicrosecs" type="microsecsType"/>
  </xs:all>
</xs:group>

<xs:group name="gpioTraccallbackPowerProfAddGroup">
  <xs:all>
    <xs:element name="durationMillisecs" type="powerProfDurationType"/>
    <xs:element name="offsetSecs" type="offsetSecsType"/>
    <xs:element name="offsetMicrosecs" type="microsecsType"/>
  </xs:all>
</xs:group>

<!-- Type definition for duration of a power profile in milliseconds -->
<xs:simpleType name="powerProfDurationType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="50"/>
    <xs:maxInclusive value="3600000"/>
  </xs:restriction>
</xs:simpleType>

<!-- Type definition for samling divider of a power profile -->
<xs:simpleType name="powerProfSamplingDividerType">
  <xs:restriction base="xs:integer">
    <xs:pattern value="1|2|4|8|16|32|64|640|6400|64000"/>
  </xs:restriction>
</xs:simpleType>

<!-- Type definition for time offset in seconds -->
<xs:simpleType name="offsetSecsType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="0"/>
    <xs:maxInclusive value="3600"/>
  </xs:restriction>
</xs:simpleType>

<!-- Type definition for time offset in microseconds -->
<xs:simpleType name="microsecsType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="0"/>
    <xs:maxInclusive value="999999"/>
  </xs:restriction>
</xs:simpleType>

<!-- Group definitions for timing groups -->
<xs:group name="timingRelativeGroup">
  <xs:all>
    <xs:element name="offsetSecs" type="offsetSecsType"/>
    <xs:element name="offsetMicrosecs" type="microsecsType" minOccurs="0" maxOccurs="1"/>
  </xs:all>
</xs:group>

<xs:group name="timingAbsoluteGroup">
  <xs:all>
    <xs:element name="absoluteDateTime" type="xs:dateTime"/>
    <xs:element name="absoluteMicrosecs" type="microsecsType" minOccurs="0" maxOccurs="1"/>
  </xs:all>
</xs:group>

<!-- Type definition for slot assignements -->
<xs:simpleType name="slotNrType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1"/>
    <xs:maxInclusive value="4"/>
  </xs:restriction>
</xs:simpleType>

<!-- Type definition for test duration in seconds -->
<xs:simpleType name="testDurationSecsType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="10"/>
  </xs:restriction>
</xs:simpleType>

<!-- Group definition for test start/end -->
<xs:group name="testDurationAbsoluteGroup">
  <xs:all>
    <xs:element name="start" type="xs:dateTime"/>
    <xs:element name="end" type="xs:dateTime"/>
  </xs:all>
</xs:group>

<!-- Type definition for unsigned int -->
<xs:simpleType name="unsignedIntType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="0"/>
    <xs:maxInclusive value="4294967295"/>
  </xs:restriction>
</xs:simpleType>

<!-- Type definitions for periodic GPIO actuations -->
<xs:simpleType name="periodicIntervalMicrosecsType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="100"/>
    <xs:maxInclusive value="3600000000"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="periodicCountType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1"/>
    <xs:maxInclusive value="4294967295"/>
  </xs:restriction>
</xs:simpleType>

<!-- Group definition for GPIO actuation periodic group -->
<xs:group name="gpioActuationPeriodicGroup">
  <xs:all>
    <xs:element name="intervalMicrosecs" type="periodicIntervalMicrosecsType"/>
    <xs:element name="count" type="periodicCountType"/>
  </xs:all>
</xs:group>

<!-- Type definition for IP addresses -->
<xs:simpleType name="ipType">
  <xs:restriction base="xs:string">
    <xs:pattern value="((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])"/>
  </xs:restriction>
</xs:simpleType>


</xs:schema>

=== ETHZ-TEC/FlockLab2-Server/testmanagementserver/linktests/linktest_tinynode.xml
<?xml version="1.0" encoding="UTF-8"?>
<testConf xmlns="http://www.flocklab.ethz.ch" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.flocklab.ethz.ch xml/flocklab.xsd">
	<!-- General configuration -->
	<generalConf>
		<name>LinkMeasurement</name>
		<description>
                        500s test tinynode
		</description>
		<scheduleAsap>
                        <durationSecs>500</durationSecs>
		</scheduleAsap>
		<!-- scheduleAbsolute>  <start>2012-05-11T08:20:00+02:00</start>
		<end>2012-05-11T08:30:00+02:00</end></scheduleAbsolute -->
		<emailResults>no</emailResults>
	</generalConf>
	
	<!-- Target configuration -->
	<targetConf>
		<obsIds>001 002 004 006 007 008 010 011 013 014 015 016 017 018 019 020 022 023 024 025 026 027 028 031 032 033</obsIds>
		<targetIds>0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25</targetIds>
		<voltage>3.3</voltage>		
		<embeddedImageId>linktest_tinynode</embeddedImageId>
	</targetConf>
	
	<!-- Serial Reader Service configuration -->
	<serialConf>
		<obsIds>001 002 004 006 007 008 010 011 013 014 015 016 017 018 019 020 022 023 024 025 026 027 028 031 032 033</obsIds>
		<port>serial</port>
		<baudrate>57600</baudrate>
		<mode>pck</mode>
	</serialConf>
	
	<!-- GPIO Actuation Service configuration -->
	<gpioActuationConf>
		<obsIds>001 002 004 006 007 008 010 011 013 014 015 016 017 018 019 020 022 023 024 025 026 027 028 031 032 033</obsIds>
		<pinConf>
			<pin>SIG1</pin>
			<level>low</level>
			<relativeTime>
				<offsetSecs>0</offsetSecs>
				<offsetMicrosecs>1000</offsetMicrosecs>
			</relativeTime>
		</pinConf>
		<pinConf>
			<pin>SIG1</pin>
			<level>high</level>
			<relativeTime>
				<offsetSecs>3</offsetSecs>
				<offsetMicrosecs>0</offsetMicrosecs>
			</relativeTime>
		</pinConf>
	</gpioActuationConf>
	<imageConf>
		<embeddedImageId>linktest_tinynode</embeddedImageId>
		<name>FlockLabLinkMeasurement</name>
		<description></description>
		<platform>tinynode</platform>
		<os>tinyos</os>
		<data>
f0VMRgEBAf8AAAAAAAAAAAIAaQABAAAAADEAADQAAAA4QAAA8QAAADQAIAAEACgACAAFAAEAAAAA
AAAAxBAAAMQQAAC0AAAA2AkAAAYAAAABAAAAAQAAALQAAAAAMQAAADEAAJQ+AACUPgAABQAAAAEA
AAABAAAASD8AAAARAACUbwAAeAAAAHgAAAAGAAAAAQAAAAEAAADAPwAAwP8AAMD/AABAAAAAQAAA
AAUAAAABAAAAMUAAMbJAgFogAT9AJAkPkwQkH4PPQ3gR/CM/QHgAD5MGJC+DQBifT5RvABH6I4AA
ukeAAGBvZlE0fGMcf2U8jnFBkHMlf2VAooIAo4I+f2VEpYQkalUEf2VIfmUNlHZDf2YBdl47eGAf
f2YFpoUlnX4UAAAhEEIgYzCEQKVQxmDncAiBKZFKoWuxjMGt0c7h7/ExEhACczJSIrVSlEL3ctZi
OZMYg3uzWqO905zD//Pe42IkQzQgBAEU5mTHdKREhVRqpUu1KIUJle7lz/WsxY3VUzZyJhEWMAbX
dvZmlVa0Rlu3eqcZlziH3/f+553XvMfESOVYhmineEAIYRgCKCM4zMnt2Y7pr/lIiWmZCqkrufVa
1Eq3epZqcRpQCjM6Eir929zLv/ue63mbWIs7uxqrpmyHfORMxVwiLAM8YAxBHK7tj/3szc3dKq0L
vWiNSZ2XfrZu1V70ThM+Mi5RHnAOn/++793f/M8bvzqvWZ94j4iRqYHKseuhDNEtwU7xb+GAEKEA
wjDjIARQJUBGcGdguYOYk/uj2rM9wxzTf+Ne87ECkBLzItIyNUIUUndiVnLqtculqJWJhW71T+Us
1Q3F4jTDJKAUgQRmdEdkJFQFRNun+reZh7iXX+d+9x3HPNfTJvI2kQawFldmdnYVRjRWTNltyQ75
L+nImemJirmrqURYZUgGeCdowBjhCII4oyh9y1zbP+se+/mL2Ju7q5q7dUpUWjdqFnrxCtAasyqS
Oi79D+1s3U3Nqr2LreidyY0mfAdsZFxFTKI8gyzgHMEMH+8+/13PfN+br7q/2Y/4nxduNn5VTnRe
ky6yPtEO8B4AABAAUACQANAA8AAPQhLDDxAPEQ8RX/MywgNDf/MQAU+TASQy0hABPxWwE0I0PBex
wPAAAAAAE8KTdREGJNJTdhHykAMAdhEBJBABsBMwNA5PHoJcEoJPXBLCQ3YRwpMREwMkwkMRExAB
PpADCBQo8pDg/1YAAyzSU1YAEAFfQlcAf/APAH+QDwDfL9JTVwDyQGAAVgAQAT6Q/gfWL8KTVgAD
JPJTVgAQAfKwDwBXAMwn8lNXAPJAgP9WAMY/HkKQAQ9OHkKQAQ+e+yMPThABH0JiAY8QX/MCJB9C
cgEQAR9CZAGPEF/zAiQfQnQBEAEfQmYBjxBf8wIkH0J2ARABPxUfQi4BEsNPEH/zH5MSJC+TCzgv
kwYkP5AFAA0gsBOqMwo8sBNiNAc8D5MFILATQjQCPLATUjQ8F7HA8AAAAAATPxVPQ7ATyDQ8F7HA
8AAAAAATEAFOT3/zP5JoLA9fEE/WNOY0AjUeNVA1YjVyNYI1kjUfQoIBjxBf8wMkH0KSARABsvDv
/4IBsBOoNRABH0KEAY8QX/MDJB9ClAEQAbLw7/+EAbATWl8QAR9ChgGPEF/zAyQfQpYBEAGy8O//
hgGCk0ISCCCCk0QSBSB/QBMAsBOIORABsBOKPxABH0KIAY8QX/MDJB9CmAEQARABH0KKAY8QX/P6
Jx9CmgEQAR9CjAGPEF/z8icfQpwBEAEfQo4BjxBf8+onH0KeARABklM6EoJjPBKSU2gSEAFPTrAT
xjTcPwsVXkIuEU9Of/Dg/8JPWhJ/8z+QQABWJD+QQQA3NA+TJiQ/kCAACCQbQiISsBMwNA5LsBNA
Pmc8T05/8B8Af9BAAMJPLhFOT09DsBOyNvLwfwAlAPLwfwAjAPLwfwAkAPLQgP8lALJAGgAiEt0/
T05/8B8Af9AgAMJPLhFOT09DsBOyNrJAoAAiEs4/P5BgAA4kP5CAAMgjsBOaN4JOKhGCTywRsBOK
N7ATXD0sPLATijewE5o3gk4qEYJPLBGwE8g3ITx+8B8Awk4uEbATijdfQhITf5BgABEkf5CA/6Qj
X0IuEX/QgP/CTy4RTk9PQ7ATsjayQBAAIhKWP19CLhF/0GAA8T8LFxABOxVJT0hODkNfQiAAX/N/
80+TASQeQ09OH/NfkwYkXkN/QAcAsBMoNw08DkNfQiAAf/AQAH/zT5MBJB5DT04f81+T7SOwE34z
Sk87QCEA+/Dv/wAASVl58D4AT0mwE2Y3T0iwE2Y3+9AQAAAAT0qwE5IzOBcQARsVSk9LTk6TDCSw
E34zwkpgGsJDYRqwE5IzTktPSrATTjcaFxABGxVLT0pOsBN+M0pbwlofErATkjMaFxABwk9vAOKy
AwAFJB9Df/NPk/knAjwPQ/o/4sIDAF9CbgB/8xAB8vB/ACUA8vB/ACMAD0MQASsVGUJoErATMDQO
Tx9CgAFf83/zT5MEJBlTsBMwNA5PD0MLSQpDDtoP2ykXEAEfQhgRL5MVJC+SASQQAV9DsBNCOF9D
sBMgPG9DsBNUOk9DsBOIOYJDGBFfQ7ATtDwQAV9DsBNCOF9DsBMgPF9DsBNUOsKTFxELIIJDGBFf
Q7ATtDxOQx9CMBKwE9I8EAGyQAUAGBGwEzA0PkD6ALATIj1fQ7ATtDzJP0+TDCRfQmcaX9PCT2ca
Tk9/QA0AsBOyNg9DEAF/QAUAsBOWOE+TAyQ/QAUAEAF/QAUAsBOyOF9CZxpf08JPZxpOT39ADQCw
E7I2f0AFALATVDriPxsVS0+wE34zSkPCmxwRASBaQ7ATkjNPShoXEAErFUlPsBN+M0pPwpMaEQUk
sBOSMz9ABQAOPE9DsBPsOEtPT5MEIMJJHBHSQxoRT0qwE5IzT0spFxABCxVLT7ATfjPCkx8RECDi
Qx8RwktMGrATkjOwE0A5X0IgEU+bCCSwE34zwkMfEbATkjMfQw08f/MPkwgkH5MCJA9DBjxfQ7AT
4Dn6P09D+z8LFxABCxWwE34zS0/ikyARBSRPS7ATkjMfQxY8X0IfEV+TDSRvk/Uj0kJMGiAR8kAD
AB8RT0uwE5IzD0MFPH9AAwCwE4g59j8LFxABCxVLT7ATfjNNTw5DT0v/k6gRGCQeQw9DTpMKIPKT
XxoOJF9CmBrPS6gRwkuYGh9DT5MDIHtABQAJPEtDBzzCS18a8z/Cm5ga5iPkP09NsBOSM09LCxcQ
ARsVPEAAAhpCAhGwE3hvgkxuGiyTAiyiQ24asBN+M05P0kNpAF9CBBFf08JPaABfQgURX9PCT2kA
0kICEWoAH0ICEY8Qf/PCT2sAP0AbAO/TAADv0gAA/9IAANLDaQDy8PP/AwDy8PP/AQBPTrATkjMa
FxABGxVLT7ATfjNKT8KbHBEKJF5Df0ALALATKDdPSrATkjMfQzE88kMcEU9DsBPeOlxCGxFMkyUk
XkIcEV5TfpAHAAEoTkNPTEtODUsNkwMkDxEdg/0jH/PxJ8JOHBEfQw5LDpMDJA9fHoP9I0zPwkwb
EU9DsBPAO09KsBOSMw9DAzzCQxoR+D8aFxABGxVLT7ATfjNKT/KQAwAfEQUkT0qwE5IzH0NhPF1C
IBFNm/cjT0NeQh0RfpNWJB/zT5M0IH6TLyRPTg5PPlAmEuJOHRHykx0RIyT+QwAAwk9MGvJDIBHS
Qx8Rf0ADALATiDlPSw+TByQfkwUkT0qwE5IzD0M0PNJDaQA/QBsA78MAAO/CAAD/wgAA0sNpAO4/
8kMeEdo/P0D/ANk/4kMgEcJDHxFPTQ+TCyQfkwkkP0AbAO/DAADvwgAA/8IAANY/0kNpAD9AGwDv
wwAA78IAAP/CAADSw2kA6j9fQ6g/GhcQAU5PwpMfESUkwp9MGiAkTUN/8/+TJhIXJF1DT009QAUA
T5MKIPKTHRELJF9CHhHPTiYSwk4eEQ1DT00/8AUAEAHCTh0R9j/Cnh4R5yPlPw9DEAHSQx8Rwk9M
GrATQDn3PwsVT5MNJF9C5BJ/0EAAwk/kEk5Pf0AOALATsjYPQyg8f0AFALATljhPkwMkP0AFAB88
f0AFALATsjh/80tPTk9/QAUAsBOUPEuTAiRPSxA8X0LkEn/QQADCT+QSTk9/QA4AsBOyNn9ABQCw
E1Q61j8LFxABTpMBIBABwk8kEsJDJRKwE6g8+D9NT09OT13CX+YSEAHSwy0A0sMrAE+TAyTSwywA
AjzS0ywA0tMtAA9DEAENTx9CIBIfkx4kH5MNKC+TASQQAU6TBSB/QA4AsBOIORABf0APAPo/TpMK
IB9CPhHPTSUAjRDPTSQAf0AQAO4/f0ARAOs/gkM+EX9ADQDmPxsVC08KTrATMDQOTw6LDpoGLAqO
OpADAAIoD1oDPLATMDQvU4JPlAE/QIQBn8MAAL/QEAAAABoXEAGikxgRASQQAbATsD1fQ7ATvD2w
EzA0DU8eQnwRD04PXw9eD18PXg5PD0MSww8QDhAPEQ4QDxEOEA8RDhAPEQ4QDV6CTTASXkISER9C
EBGwE9o92T/Swy0A0sMrAA9DEAHiwy0A4sMrAE+TAyTiwywAAjzi0ywA4tMtAA9DEAE7FUhOCU8O
Q19CIABf83/zT5MBJB5DT04f80+TDSQOQ19CIAB/8BAAf/NPkwEkHkNPTh/zT5MEIF5Df0KwEyg3
SkNKmA0sO0AhANvDAABvSbATZjfb0wAAGVNaU0qY8ysPQzgXEAEbFQtPCk6wEzA0Dk8Oiw6aBiwK
jjqQAwACKA9aAzywEzA0L1OCT5IBP0CCAZ/DAAC/0BAAAAAaFxABKxULT0lOCk1MkzUgHEI+EQyT
AyR+kAkAOCTCk0ARKyDSQ0AR20JsEicAeVD5/8tJJgDLSiUAihDLSiQAXUJEEU2TCSRfSwEAjxBe
SwIAD94fkgAREiTbswcAAiRNkwkkf0ANALATiDkfQkIRgktCETk8wkNAEQ9LNTzbswcA6yfCQ0QR
f0ASAO0/XUsDAI0QX0sEAA3fX0wBAI8QXkwCAA/eDZ+6I19LAQCPEF5LAgAP3h+SABGxI9ybBQAF
AK0j3JsGAAYAqSNfSwgAjxBeSwkAD96CT8oR0kMaE9xCbBInAMk/KRcQAX5Aif9/QBYAsBOyNn5A
NAB/QBcAsBOyNn5AVgB/QBgAsBOyNg9DEAF7FSGCsBOIQAZOB0+BTgAAgU8CAB5CTBIfQk4SFEJC
EhVCRBIMTg1PDFQNZQhMCU0Ihgl3CkYLRwqOC39LKApMC00Kjgt/BygORg9HDowPfQIoCEMJQwxI
DUk8gAEEDXMwKC5BH0ECAD5QAAQPY4JOTBKCT04SOFAA/DljgkhCEoJJRBI4QAAECUMLRgtbC1sL
WwtbC1sKSApaCloKWgpaClqwEzA0Dk8Oiw6aBiwKjjqQAwACKA9aFjywEzA0L1MSPIJUTBKCZU4S
gkNCEoJDRBLbPwpMC00Kjgt/ui8uQR9BAgCzP4JPlgE/QIYBn8MAAL/QEAAAACFSdBcQASsVsBN+
M0lPGkI6EhtCPBKwEzA0Dk8fQoABX/N/80+TBSQaUwtjsBMwNA5PD04Sww8QDxEPEQ8RDxEOTw9D
S+oL6osQevOKEApaC2sKWgtrCloLawreC99PSbATkjMOSg9LKRcQAT8VH0IeARLDTxCwE8g0PBex
wPAAAAAAE08V0rMDAAUk0rMBAAIkW0JmAOKyAwATJOKyAQAQJFtCbgCwE05BT5MKJLATBkJ/8w+T
AiQfkwMgT0uwE1xBSxexwPAAAAAAE8KTHxECIA9DEAEfQxABCxVOT4KT4BIGJB9COBLPTgAAklM4
Eh1CPhIbQmQaD00PWx5CehEOnzksDZM1JG9Owk9vAB5Tgk56EQxOHFJuGg9ND1sPnAEsDE8OnCws
gpM+EiAkH0J6EW5P4rIDABgkH0N/80+T+SfCTm8AX0JuAE5PgpPgEgYkH0I4Es9OAACSUzgSklN6
EYKcehHgKws8D0PnP05D4T9PQ8o/4sIBAG9DsBOIOQsXEAHykAMAHxEDJD9A/wAQAV9CIBEQAT8V
4rMDAAIk4sMDAPKyAwAIJPLCAwCwE05BT5MCJLATBkI8F7HA8AAAAAATPxUhg19CIwBf8iUAf/OB
TwAAkbMAAAMk0sMjAEg8obMAAAMk4sMjAEI8obIAAA0k4sIjALATAEPywiUA8sIjAH9ACgCwE4g5
MjyxsgAAAyTywiMA7z+xsBAAAAAEJPLw7/8jACQ8sbAgAAAABCTy8N//IwAcPLGwQAAAAAQk8vC/
/yMAFDwvQU+TETTy8H8AIwCwE4o3H0KCAX/wEAB/80+TAySy8O//ggGwE6g1IVM8F7HA8AAAAAAT
4sIlAOLCIwAPQxABPxUhg19CKwBf8i0Af/OBTwAAkbMAAAUk0sMrALATnkMyPKGzAAAFJOLDKwCw
E9JEKjyhsgAAAyTiwisAJDyxsgAAAyTywisAHjyxsBAAAAAEJPLw7/8rABY8sbAgAAAABCTy8N//
KwAOPLGwQAAAAAQk8vC//ysABjwvQU+TAzTy8H8AKwAhUzwXscDwAAAAABMhgx9CGBE/kAUAVSQ/
kAYATSwPk1QgsBOwPU9DsBOyOE+TKSSykAUAGBEeJLJABgAYEbATMDSCT0gSsBMwND5A0AewEyI9
X0OwE7w9wpMaEQMk0tMbETM8wkMcEdJDGhFPQ7ATwDsrPMJDFxFeQw9DsBPSPCQ8gpMYEREkDkF/
QBQAsBNgROJBbBKwEzA0PkDQB7ATIj1fQ7ATvD0QPJJDGBGwEzA0gk9IEug/P5IHLLJCGBEEPLLw
7/+EAaw/IVMQASsVSk8JTg5DX0IgAF/zf/NPkwEkHkNPTh/zX5MGJF5Df0AGALATKDcNPA5DX0Ig
AH/wEAB/80+TASQeQ09OH/Nfk+0jO0AhAPvw7/8AAEpaevB+AHrQQABPSrATZjdPQ7ATZjfJTwAA
+9AQAAAAKRcQAR9CGBEvkx4kP5ADAAssH5MBJBABsvDv/4QBsBNQRbATXEUQAT+QBQD1Jz+QBgAB
JBABsvDv/4QBsBNQRbJABwAYERABsBNQRbATpEbSkxcRAySwE2I/7D9+QBIAf0AWALATsjZ+QD8A
f0AXALATsjZ+QO3/f0AYALATsjYQAeLDLQDiwysAD0MQARsVXkIWER9CFBGwEzRGG0IUEeJLExFd
QhMRTk1aQhYRTEoPTC9TD54DNH2QJQAbKLKQBQAYEREksBNiP19DsBNCOF9DsBMgPIJDGBFfQ7AT
tDxPQ7ATVDo9PE5DH0IwErAT0jzpPwtcTYpdU05ND0uwEzRGsBNiP19DsBNCOF9DsBMgPE9DsBNU
OoJDGBFfQ7ATtDzCkxcREiTCQxcRTEMNQ15CExEfQhQRsBN6PoJPFBFOQx9CMBKwE9I8CzxMQx1C
SBJeQhMRH0IUEbATej6CTxQRGhcQATsVSE4JTw5DX0IgAF/zf/NPkwEkHkNPTh/zX5MYJF5Df0AF
ALATKDdKQ0qYHiw7QCEA28MAAE9DsBNmN8lPAADb0wAAGVNaU0qY8SsOPA5DX0IgAH/wEAB/80+T
ASQeQ09OH/Nfk9sj3z8PQzgXEAEbFT9AKgDfwwAA78MAAPLw3/8aAPLwfwAiALATmjcMTg1PW0Iu
EUpLevDg/3qQgP9nJHqQYABbJPJAYAASE8JKWhJPSj+QQAA0JD+QQQArNA+TGiQ/kCAACCQbQiIS
sBMwNA5LsBNAPlQ8T0t/8B8Af9BAAMJPLhFOT09DsBOyNrJAGgAiEuk/T0t/8B8Af9AgAMJPLhFO
